# Generated by Django 4.2.28 on 2026-02-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('events_json', models.JSONField(default=list)),
                ('video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('share_token', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
