# Generated by Django 4.2.28 on 2026-07-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlight_app', '0002_analysissession_user_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
